# Generated by Django 3.1.1 on 2020-09-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Variants',
            new_name='Variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_default',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='variant',
            new_name='variant_type',
        ),
    ]
