# Generated by Django 3.1.1 on 2020-09-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200928_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='minamount',
            new_name='minimum_quantity',
        ),
    ]
