# Generated by Django 3.1.1 on 2020-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200930_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='compare_at_price',
        ),
        migrations.AddField(
            model_name='product',
            name='continue_selling_when_out_of_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_keeping_unit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
