# Generated by Django 3.1.1 on 2020-09-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200930_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_keeping_unit',
            field=models.IntegerField(default=0),
        ),
    ]
