# Generated by Django 3.1.1 on 2020-10-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200930_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='minimum_quantity',
            new_name='minimum_quantity_to_sell',
        ),
    ]
