# Generated by Django 3.1.1 on 2020-09-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200921_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_Info',
            new_name='customer',
        ),
    ]
