# Generated by Django 3.1.1 on 2020-09-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='continue_selling_when_out_of_stock',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_keeping_unit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
