# Generated by Django 3.1.1 on 2020-09-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200924_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='continue_selling_when_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
