# Generated by Django 3.1.1 on 2020-09-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200924_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='details',
        ),
    ]
